### PR TITLE
WIP: ITK fix for resolution bug

### PR DESCRIPTION
**Pull request by hjmjohnson**
This provides a working version of ANTS
for convering displacements to/from itk::Image
and itk::Transform without loss of precision.

Fixes https://github.com/stnava/ANTs/issues/74

Do not push this yet.  We need to wait for ITK to incorporate a patch.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@ntustison Nick,  I think this also needs to be updated.  Both of us are trying to get the new ants to work!

**Comment by hjmjohnson** [comment]
@ntustison I'm building now and wil let you know how it goes.

**Comment by hjmjohnson** [comment]
@ntustison NOTE: Travis is failing becuase cmake 2.8.7 is the latest version installed on the integration servers.

**Comment by hjmjohnson** [comment]
@ntustison 
[ 70%] Completed 'ANTS'
[100%] Built target ANTS!

YEAH!

**Comment by ntustison** [comment]
Perfect!!  

Yeah, I noted on another issue that it appears to still be an open issue for travis as to when they are going to update beyond 2.8.7 despite the number of people that are asking for an update.

**Pull request merged**
