### PR TITLE
ENH: add some tests for antsRegistration in float mode

### PR DESCRIPTION
**Pull request by aghayoor**
Recently, antsRegistration is enhanced to be able to process data in single
precision. The related changes were pushed to ANTs repository, but there
were no test related to them.
The problem was that new tests could not be feeded by double type initial
transforms.
I converted those double type initial transforms to single precision
type using the newly enhanced BRAINSTransformConvert tool.
Then, I added some tests for the antsRegistration in single precision
mode. Test changes and related baselines are commited here.

### CODE REVIEW

**Comment by aghayoor** [comment]
@hjmjohnson @stnava 
Please review this pull request.

**Comment by stnava** [comment]
hi ali - added you as collaborator if you'd like to commit (at least safe)
things such as this w/o pull requests


brian

**Comment by aghayoor** [comment]
That's great! Thank you Brian.

Ali

**Comment by hjmjohnson** [comment]
@aghayoor Ali,  You have grouped two patches together in this pull request.  Please remove the changes to compare composite transforms from the added tests.

**Comment by aghayoor** [comment]
That is fixed now!

**Pull request merged**
