### PR TITLE
Add option for MINC2 support to superbuild

### PR DESCRIPTION
**Pull request by gdevenyi**
Added support for MINC2 in superbuild

### CODE REVIEW

**Comment by vfonov** [comment]
I made changes to v2.1.0 to work properly with minc-style transformation files. Should I send a merge request?

**Comment by ntustison** [comment]
Hi Vlad, I defer to Brian on this but he's currently traveling so he'll have to weigh in when he gets a chance.  Thanks.

**Comment by gdevenyi** [comment]
@vfonov Yes please, xfm/mnc support for the transforms would be very helpful in my existing toolchains.

**Comment by gdevenyi** [comment]
Hrmm, travis build is failing because travis has old cmake.

**Comment by ntustison** [comment]
https://github.com/travis-ci/travis-ci/issues/2030

**Comment by gdevenyi** [comment]
I think this PR needs to be merged for the MINC features merged from @vfonov to work properly, in fact, I think given the merged code MINC always has to be built now for ANTS to work...?

**Comment by gdevenyi** [comment]
Still waiting on this patch to be merged. All it does is add MINC as a configuration option during the build...

**Pull request merged**
