### PR TITLE
Fix initialization per stage

### PR DESCRIPTION
**Pull request by aghayoor**

### CODE REVIEW

**Comment by aghayoor** [comment]
@hjmjohnson : Please review this pull request.
As I noticed, the combination of transforms is very prone to numerical precision. Whenever "antsRegistrationTest_initialize_transforms_per_stage" is run, generates slightly! different results.
Therefore, sometimes "antsRegistrationTest_initializePerStage_ComparisonTesting" test is fails, sometimes it is passed even if I choose very loose tolerance like 1e-1!

**Comment by hjmjohnson** [comment]
@aghayoor Testing values of a transform is not going to be very reproducible due to the iterative multiprocessor floating point accumulation problem.

**Comment by hjmjohnson** [comment]
The test should always pass.  Even if the test is not very precise.

**Comment by aghayoor** [comment]
@hjmjohnson :
Pull request is updated and the added two tests always pass.

**Pull request merged**
