### PR TITLE
Add auto versioning

### PR DESCRIPTION
**Pull request by hjmjohnson**
@satra @ntustison @stnava 

In order to better support nipype, I have added an initial bit of logic for adding versioning information to ANTs.  I arbitrarily chose the MAJOR_VERSION to be 15.

NOTE: I only instrumented the antsRegistration tool.  Someone else will need to copy-n-paste the command line processing code for "--version" and "-v" command line options to the other programs.

### CODE REVIEW

**Comment by armaneshaghi** [comment]
@hjmjohnson  Thanks, shall we put version to 2.1 to be included in the version coming soon?

**Comment by stnava** [comment]
yes - agree w/that arman


brian

**Comment by armaneshaghi** [comment]
I will merge this and add version to other programs as @hjmjohnson instructed.

**Comment by hjmjohnson** [comment]
@armaneshaghi @stnava Changed patch to be version 2.1 as requested.  It should now be ready to merge.

**Comment by satra** [comment]
@hjmjohnson - i think it would be good to leave a git trail following the minor version `2.1.0-git_short_hash`. this way for releases only the major/minor/patch needs to be updated, and you get the added benefit of always knowing the githash as well.

**Comment by hjmjohnson** [comment]
@satra This is the way it is configured.  You must manually set the MAJOR,MINOR,PATCH versions, but the git_short_hash is auto populated by cmake during compilation.

**Comment by satra** [comment]
@hjmjohnson - great

**Pull request merged**
