### PR TITLE
cmake: quote optimization flag for compiler check

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Reference: https://github.com/stnava/ANTs/issues/234
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by stnava** [comment]
note - this fails on clang.  i did not check why but we would like it to pass, of course.

**Comment by ignatenkobrain** [comment]
```
0.21s$ if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget http://www.cmake.org/files/v3.2/cmake-3.2.0-rc1-Linux-x86_64.sh; sh cmake-3.2.0-rc1-Linux-x86_64.sh --skip-license --prefix=${HOME}; export PATH=$HOME/bin/:$PATH; fi
--2015-11-02 19:32:17--  http://www.cmake.org/files/v3.2/cmake-3.2.0-rc1-Linux-x86_64.sh
Resolving www.cmake.org (www.cmake.org)... 66.194.253.19
Connecting to www.cmake.org (www.cmake.org)|66.194.253.19|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://cmake.org/files/v3.2/cmake-3.2.0-rc1-Linux-x86_64.sh [following]
--2015-11-02 19:32:17--  http://cmake.org/files/v3.2/cmake-3.2.0-rc1-Linux-x86_64.sh
Resolving cmake.org (cmake.org)... 66.194.253.19
Connecting to cmake.org (cmake.org)|66.194.253.19|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://cmake.org/files/v3.2/cmake-3.2.0-rc1-Linux-x86_64.sh [following]
--2015-11-02 19:32:17--  https://cmake.org/files/v3.2/cmake-3.2.0-rc1-Linux-x86_64.sh
Connecting to cmake.org (cmake.org)|66.194.253.19|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name `cmake.org'.
To connect to cmake.org insecurely, use `--no-check-certificate'.
sh: 0: Can't open cmake-3.2.0-rc1-Linux-x86_64.sh
```
@stnava it was problem with travis, not with my patch ) do you know how to retrigger this?

**Comment by stnava** [comment]
i restarted so let us see how this goes this time around.


brian

**Comment by ignatenkobrain** [comment]
@stnava the same problem. this could be fixed by adding `--no-check-certificate` inside travis, but it looks very strange.

**Comment by stnava** [comment]
right - not sure this new failure is related to any changes you made ... i
will not have time to check carefully until later.


brian

**Comment by ignatenkobrain** [comment]
it's defenitely not my patchset problem. Looks like travis CI spoofing SSL certificates O_o. try to retrigger CI when you will have time.

**Pull request merged**
