### PR TITLE
Revert "Vtk examples fix"

### PR DESCRIPTION
**Pull request by ntustison**
Reverts stnava/ANTs#366

### CODE REVIEW

**Comment by ntustison** [comment]
Reverting back due to the Travis fails.

**Comment by gdevenyi** [comment]
Looks like my portion of the patch fixes stuff and doesn't break travis: https://s3.amazonaws.com/archive.travis-ci.org/jobs/163144312/log.txt

But I can't re-submit the PR because mine was integrated into this one.

**Comment by ntustison** [comment]
Why don't you create a new pull request combining both patches?  Then we can verify that this new patch doesn't break travis.

**Comment by gdevenyi** [comment]
Can do, just need to figure out how :-)

**Comment by ntustison** [comment]
Great.  Thanks.

**Pull request merged**
